QLSach/QLSach/Controllers/MasterDetailController.cs
using QLSach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLSach.Controllers
{
    public class MasterDetailController : Controller
    {
        BookShopEntities db = new BookShopEntities();
        // GET: MasterDetail
        public ActionResult Index()
        {
            List<tb_PhieuNhap> lists = db.tb_PhieuNhap.ToList();
            return View(lists);
        }
        [HttpGet]
        public JsonResult GetSearchValue(string search)
        {
            var allsearch = db.tb_Sach.Where(x => x.maSach.Contains(search)).ToList();
            SelectList ls = new SelectList(allsearch, "maSach", "tieuDe");
            return new JsonResult { Data = ls, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

QLSach/QLSach/Controllers/tb_GianHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLSach.Models;
using PagedList;

namespace QLSach.Controllers
{
    public class tb_GianHangController : Controller
    {
        private BookShopEntities db = new BookShopEntities();

        // GET: tb_GianHang
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.MaSortParm = sortOrder == "ma" ? "ma_desc" : "ma";
            ViewBag.TenSortParm = sortOrder == "ten" ? "ten_desc" : "ten";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var model = db.tb_GianHang.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                model = model.Where(s => s.maGianHang.Contains(searchString)
                                       || s.tenGianHang.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "ma_desc":
                    model = model.OrderByDescending(s => s.maGianHang);
                    break;
                case "ten":
                    model = model.OrderBy(s => s.tenGianHang);
                    break;
                case "ten_desc":
                    model = model.OrderByDescending(s => s.tenGianHang);
                    break;
                default:
                    model = model.OrderBy(s => s.maGianHang);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        // GET: tb_GianHang/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_GianHang tb_GianHang = db.tb_GianHang.Find(id);
            if (tb_GianHang == null)
            {
                return HttpNotFound();
            }
            return View(tb_GianHang);
        }

        // GET: tb_GianHang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tb_GianHang/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maGianHang,tenGianHang,moTa")] tb_GianHang tb_GianHang)
        {
            if (ModelState.IsValid)
            {
                db.tb_GianHang.Add(tb_GianHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tb_GianHang);
        }

        // GET: tb_GianHang/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_GianHang tb_GianHang = db.tb_GianHang.Find(id);
            if (tb_GianHang == null)
            {
                return HttpNotFound();
            }
            return View(tb_GianHang);
        }

        // POST: tb_GianHang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "maGianHang,tenGianHang,moTa")] tb_GianHang tb_GianHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_GianHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tb_GianHang);
        }

        // GET: tb_GianHang/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_GianHang tb_GianHang = db.tb_GianHang.Find(id);
            if (tb_GianHang == null)
            {
                return HttpNotFound();
            }
            return View(tb_GianHang);
        }

        // POST: tb_GianHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_GianHang tb_GianHang = db.tb_GianHang.Find(id);
            db.tb_GianHang.Remove(tb_GianHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLSach/QLSach/Controllers/tb_NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLSach.Models;

namespace QLSach.Controllers
{
    public class tb_NguoiDungController : Controller
    {
        private BookShopEntities db = new BookShopEntities();

        // GET: tb_NguoiDung
        public ActionResult Index()
        {
            return View(db.tb_NguoiDung.ToList());
        }

        // GET: tb_NguoiDung/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_NguoiDung tb_NguoiDung = db.tb_NguoiDung.Find(id);
            if (tb_NguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(tb_NguoiDung);
        }

        // GET: tb_NguoiDung/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tb_NguoiDung/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaiKhoan,MatKhau")] tb_NguoiDung tb_NguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.tb_NguoiDung.Add(tb_NguoiDung);
                db.SaveChanges();
                setAlert("Thêm người dùng thành công","success");
                return RedirectToAction("Index");
            }

            return View(tb_NguoiDung);
        }

        // GET: tb_NguoiDung/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_NguoiDung tb_NguoiDung = db.tb_NguoiDung.Find(id);
            if (tb_NguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(tb_NguoiDung);
        }

        // POST: tb_NguoiDung/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaiKhoan,MatKhau")] tb_NguoiDung tb_NguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_NguoiDung).State = EntityState.Modified;
                db.SaveChanges();
                setAlert("Sửa người dùng thành công", "success");
                return RedirectToAction("Index");
            }
            return View(tb_NguoiDung);
        }

        // GET: tb_NguoiDung/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_NguoiDung tb_NguoiDung = db.tb_NguoiDung.Find(id);
            if (tb_NguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(tb_NguoiDung);
        }

        // POST: tb_NguoiDung/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_NguoiDung tb_NguoiDung = db.tb_NguoiDung.Find(id);
            db.tb_NguoiDung.Remove(tb_NguoiDung);
            db.SaveChanges();
            setAlert("Xóa người dùng thành công", "success");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        protected void setAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            if (type == "success")
            {
                TempData["AlertType"] = "alert-success";
            }
            else if(type == "warning")
            {
                TempData["AlertType"] = "alert-warning";
            }
            else if (type == "error")
            {
                TempData["AlertType"] = "alert-danger";
            }
        }
    }
}

QLSach/QLSach/Controllers/tb_SachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLSach.Models;
using PagedList;

namespace QLSach.Controllers
{
    public class tb_SachController : Controller
    {
        private BookShopEntities db = new BookShopEntities();

        // GET: tb_Sach
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.MaSortParm = sortOrder == "ma"? "ma_desc" : "ma";
            ViewBag.TenSortParm = sortOrder == "ten" ? "ten_desc" : "ten";
            ViewBag.SoLuongSortParm = sortOrder == "soluong" ? "soluong_desc" : "soluong";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var models = db.tb_Sach.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                models = models.Where(s => s.maSach.Contains(searchString)
                                       || s.tieuDe.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "ma_desc":
                    models = models.OrderByDescending(s => s.maSach);
                    break;
                case "ten":
                    models = models.OrderBy(s => s.tieuDe);
                    break;
                case "ten_desc":
                    models = models.OrderByDescending(s => s.tieuDe);
                    break;
                case "soluong":
                    models = models.OrderBy(s => s.soLuongTon);
                    break;
                case "soluong_desc":
                    models = models.OrderByDescending(s => s.soLuongTon);
                    break;
                default:
                    models = models.OrderBy(s => s.maSach);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(models.ToPagedList(pageNumber, pageSize));
        }

        // GET: tb_Sach/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Sach tb_Sach = db.tb_Sach.Find(id);
            if (tb_Sach == null)
            {
                return HttpNotFound();
            }
            return View(tb_Sach);
        }

        // GET: tb_Sach/Create
        public ActionResult Create()
        {
            ViewBag.maGianHang = new SelectList(db.tb_GianHang, "maGianHang", "tenGianHang");
            ViewBag.maNXB = new SelectList(db.tb_NXB, "maNXB", "tenNXB");
            return View();
        }

        // POST: tb_Sach/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[HttpPost, ValidateInput(false)]
        public ActionResult Create(HttpPostedFileBase anh, [Bind(Include = "maSach,tieuDe,tacGia,namXuatBan,giaBia,maNXB,soLuongTon,maGianHang,moTa")] tb_Sach tb_Sach)
        {
            if(anh!=null)
            {
                string path = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(anh.FileName));
                anh.SaveAs(path);
                tb_Sach.anh = anh.FileName;
            }
            if (ModelState.IsValid)
            {
                db.tb_Sach.Add(tb_Sach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.maGianHang = new SelectList(db.tb_GianHang, "maGianHang", "tenGianHang", tb_Sach.maGianHang);
            ViewBag.maNXB = new SelectList(db.tb_NXB, "maNXB", "tenNXB", tb_Sach.maNXB);
            return View(tb_Sach);
        }

        // GET: tb_Sach/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Sach tb_Sach = db.tb_Sach.Find(id);
            if (tb_Sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.maGianHang = new SelectList(db.tb_GianHang, "maGianHang", "tenGianHang", tb_Sach.maGianHang);
            ViewBag.maNXB = new SelectList(db.tb_NXB, "maNXB", "tenNXB", tb_Sach.maNXB);
            return View(tb_Sach);
        }

        // POST: tb_Sach/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]

        [HttpPost, ValidateInput(false)]  //Không cho validate dữ liệu
        public ActionResult Edit(HttpPostedFileBase anh, tb_Sach tb_Sach)
        {
            if (anh != null)
            {
                string path = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(anh.FileName));
                anh.SaveAs(path);
                tb_Sach.anh = anh.FileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(tb_Sach).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.maGianHang = new SelectList(db.tb_GianHang, "maGianHang", "tenGianHang", tb_Sach.maGianHang);
            ViewBag.maNXB = new SelectList(db.tb_NXB, "maNXB", "tenNXB", tb_Sach.maNXB);
            return View(tb_Sach);
        }

        // GET: tb_Sach/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Sach tb_Sach = db.tb_Sach.Find(id);
            if (tb_Sach == null)
            {
                return HttpNotFound();
            }
            return View(tb_Sach);
        }

        // POST: tb_Sach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tb_Sach tb_Sach = db.tb_Sach.Find(id);
            db.tb_Sach.Remove(tb_Sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLSach/QLSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--
Template Name: Corporation
Author: <a href="http://www.os-templates.com/">OS Templates</a>
Author URI: http://www.os-templates.com/
Licence: Free to use under our free template licence terms
Licence URI: http://www.os-templates.com/template-terms
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Book Store</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <link rel="stylesheet" href="~/Theme/corporation/layout/styles/layout.css" type="text/css" />
</head>

<body id="top">

    <div class="wrapper col1">
        <div id="head">
            <h1>@Html.ActionLink("BookStore", "Index", "Home")</h1>
            <p>Quản lý cửa hàng sách</p>
            <div id="topnav">
                <ul>
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sách", "Index", "tb_Sach")</li>
                    <li>@Html.ActionLink("Gian hàng", "Index", "tb_GianHang")</li>
                    <li>@Html.ActionLink("Người dùng", "Index", "tb_NguoiDung")</li>
                    <li>
                        @Html.ActionLink("Hóa đơn", "Index", "MasterDetail")
                        <ul>
                            <li>@Html.ActionLink("Phiếu nhập", "Index", "MasterDetail")</li>
                            <li>@Html.ActionLink("Phiếu xuất", "Index", "tb_PhieuXuat")</li>
                        </ul>
                    </li>
                    @*<li>@Html.ActionLink("Thông tin", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Đăng xuất", "Logout", "Home")</li>
                </ul>
            </div>
            @*<div id="search">
                <form action="#" method="post">
                    <fieldset>
                        <legend>Site Search</legend>
                        <input type="submit" name="go" id="go" value="GO" />
                        <input type="text" value="Search the site&hellip;" onfocus="this.value=(this.value=='Search the site&hellip;')? '' : this.value ;" />
                    </fieldset>
                </form>
            </div>*@
        </div>
    </div>
    <div class="wrapper col4">
        <div id="container">
            @RenderBody()
        </div>
    </div>
    <div class="wrapper col5">
        <div id="footer">
            <div id="contactform">
                <h2>Liên hệ với chúng tôi</h2>
                <form action="#" method="post">
                    <fieldset>
                        <legend>Đăng ký</legend>
                        <label for="fullname">
                            Tên:
                            <input id="fullname" name="fullname" type="text" value="" />
                        </label>
                        <label for="emailaddress" class="margin">
                            Email:
                            <input id="emailaddress" name="emailaddress" type="text" value="" />
                        </label>
                        <label for="phone">
                            Số điện thoại:
                            <input id="phone" name="phone" type="text" value="" />
                        </label>
                        <label for="subject" class="margin">
                            Công việc:
                            <input id="subject" name="subject" type="text" value="" />
                        </label>
                        <label for="message">
                            Ghi chú:<br />
                            <textarea id="message" name="message" cols="40" rows="4"></textarea>
                        </label>
                        <p>
                            <input id="submitform" name="submitform" type="submit" value="Đăng ký" />
                            &nbsp;
                            <input id="resetform" name="resetform" type="reset" value="Nhập lại" />
                        </p>
                    </fieldset>
                </form>
            </div>
            <!-- End Contact Form -->
            <div id="compdetails">
                <div id="officialdetails">
                    <h2>Dịch vụ</h2>
                    <ul>
                        <li><a href="#">Điều khoản sử dụng</a></li>
                        <li><a href="#">Chính sách bảo mật</a></li>
                        <li><a href="#">Giới thiệu Book Store</a></li>
                        <li class="last">VAT No. 123</li>
                    </ul>
                    <h2>Knowledge is power !</h2>
                    <p><a href="tel:0987654321">0987654321</a> | <a href="tel:0999999999">0999999999</a></p>
                </div>
                <div id="contactdetails">
                    <h2>Thông tin cửa hàng !</h2>
                    <ul>
                        <li>BookStore</li>
                        <li>235 Hoàng Quốc Việt Hà Nội</li>
                        <li>Tel: <a href="tel:0987654321">0987 654 321</a> <a href="tel:0999999999">0999 999 999</a></li>
                        <li>Fax: xxxxx xxxxxxxxxx</li>
                        <li>Email: info@bookstore.com</li>
                        <li class="last">LinkedIn: <a href="#">BookStore Profile</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <!-- End Company Details -->
            <div id="copyright">
                <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved - <a href="#">Domain Name</a></p>
                <p class="fl_right">Template by <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
                <br class="clear" />
            </div>
            <div class="clear"></div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

QLSach/QLSach/Views/Shared/_Layout1.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--
Template Name: Corporation
Author: <a href="http://www.os-templates.com/">OS Templates</a>
Author URI: http://www.os-templates.com/
Licence: Free to use under our free template licence terms
Licence URI: http://www.os-templates.com/template-terms
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Book Store</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <link rel="stylesheet" href="~/Theme/corporation/layout/styles/layout.css" type="text/css" />
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    <style>
        body{
            padding-top:0px;
        }
        a:hover{
            text-decoration:none;
        }
    </style>
</head>

<body id="top">

    <div class="wrapper col1">
        <div id="head">
            <h1>@Html.ActionLink("BookStore", "Login", "Home")</h1>
            <p>Quản lý cửa hàng sách</p>
            <div id="topnav">
                <ul>
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sách", "Index", "tb_Sach")</li>
                    <li>@Html.ActionLink("Gian hàng", "Index", "tb_GianHang")</li>
                    <li>@Html.ActionLink("Người dùng", "Index", "tb_NguoiDung")</li>
                    <li>@Html.ActionLink("Hóa đơn", "Index", "MasterDetail")
                        <ul>
                            <li>@Html.ActionLink("Phiếu nhập", "Index", "MasterDetail")</li>
                            <li>@Html.ActionLink("Phiếu xuất", "Index", "tb_PhieuXuat")</li>
                        </ul>
                    </li>
                    @*<li>@Html.ActionLink("Thông tin", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Đăng xuất", "Logout", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="wrapper col4">
        <div id="container">
            @RenderBody()
        </div>
    </div>
    <div class="wrapper col5">
        <div id="footer">
            <div id="contactform">
                <h2>Liên hệ với chúng tôi</h2>
                <form action="#" method="post">
                    <fieldset>
                        <legend>Đăng ký</legend>
                        <label for="fullname">
                            Tên:
                            <input id="fullname" name="fullname" type="text" value="" />
                        </label>
                        <label for="emailaddress" class="margin">
                            Email:
                            <input id="emailaddress" name="emailaddress" type="text" value="" />
                        </label>
                        <label for="phone">
                            Số điện thoại:
                            <input id="phone" name="phone" type="text" value="" />
                        </label>
                        <label for="subject" class="margin">
                            Công việc:
                            <input id="subject" name="subject" type="text" value="" />
                        </label>
                        <label for="message">
                            Ghi chú:<br />
                            <textarea id="message" name="message" cols="40" rows="4"></textarea>
                        </label>
                        <p>
                            <input id="submitform" name="submitform" type="submit" value="Đăng ký" />
                            &nbsp;
                            <input id="resetform" name="resetform" type="reset" value="Nhập lại" />
                        </p>
                    </fieldset>
                </form>
            </div>
            <!-- End Contact Form -->
            <div id="compdetails">
                <div id="officialdetails">
                    <h2>Dịch vụ</h2>
                    <ul>
                        <li><a href="#">Điều khoản sử dụng</a></li>
                        <li><a href="#">Chính sách bảo mật</a></li>
                        <li><a href="#">Giới thiệu Book Store</a></li>
                        <li class="last">VAT No. 123</li>
                    </ul>
                    <h2>Knowledge is power !</h2>
                    <p><a href="tel:0987654321">0987654321</a> | <a href="tel:0999999999">0999999999</a></p>
                </div>
                <div id="contactdetails">
                    <h2>Thông tin cửa hàng !</h2>
                    <ul>
                        <li>BookStore</li>
                        <li>235 Hoàng Quốc Việt Hà Nội</li>
                        <li>Tel: <a href="tel:0987654321">0987 654 321</a> <a href="tel:0999999999">0999 999 999</a></li>
                        <li>Fax: xxxxx xxxxxxxxxx</li>
                        <li>Email: info@bookstore.com</li>
                        <li class="last">LinkedIn: <a href="#">BookStore Profile</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <!-- End Company Details -->
            <div id="copyright">
                <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved - <a href="#">Domain Name</a></p>
                <p class="fl_right">Template by <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
                <br class="clear" />
            </div>
            <div class="clear"></div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>